spring.application.name=recrutement


jwt.secret=ahgfd543326hgfs7'*mvfe$l&'"(66yG"(-yopg,v85643gfr$$
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/recruitment
spring.datasource.username=............
spring.datasource.password=...........
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.thymeleaf=DEBUG





spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/


spring.rabbitmq.queue=email.queue
spring.rabbitmq.registration-queue=registration-queue
spring.rabbitmq.exchange=user.registration.exchange
spring.rabbitmq.routing-key=user.registered


spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=10


spring.mail.host=smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=8a982777400e77
spring.mail.password=cf1cccfbb30d7d
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.mail=DEBUG
logging.level.org.apache.commons.net=DEBUG
logging.level.org.springframework.integration.mail=DEBUG
